name: ServiceNow GitHub Action tester

on:
  workflow_dispatch:

jobs:
  ServiceNow-GitHub-Actions-Test-Legacy:
    environment: LEGACY  
    runs-on: ubuntu-latest
    steps:
       - name: Run Tests Legacy
         uses: mikevdberge/sncicd-tests-run@1.0.11
         with:
            testSuiteSysId: 891763283b5c22101680fec5e4e45a21
         env:
            nowUsername: ${{ secrets.NOW_USERNAME }}
            nowPassword: ${{ secrets.NOW_PASSWORD }}
            nowInstallInstance: ${{ vars.NOW_INSTALL_INSTANCE }}

  ServiceNow-GitHub-Actions-Test-API-Key:
    environment: API-KEY  
    runs-on: ubuntu-latest
    needs: ServiceNow-GitHub-Actions-Test-Legacy
    steps:
       - name: Run Tests API Key
         uses: mikevdberge/sncicd-tests-run@1.0.11
         with:
            testSuiteSysId: 891763283b5c22101680fec5e4e45a21
         env:
            nowApikey:  ${{ secrets.NOW_APIKEY }}
            nowFullInstance: ${{ vars.NOW_FULL_INSTANCE }}

  ServiceNow-GitHub-Actions-Test-Basic-Auth:
    environment: BASIC-AUTH 
    runs-on: ubuntu-latest
    needs: ServiceNow-GitHub-Actions-Test-API-Key
    steps:
       - name: Run Tests Basic Auth
         uses: mikevdberge/sncicd-tests-run@1.0.11
         with:
            testSuiteSysId: 891763283b5c22101680fec5e4e45a21
         env:
            nowUsername: ${{ secrets.NOW_USERNAME }}
            nowPassword: ${{ secrets.NOW_PASSWORD }}            
            nowFullInstance: ${{ vars.NOW_FULL_INSTANCE }}

  ServiceNow-GitHub-Actions-Test-HMAC-Token:
    environment: HMAC-Token  
    runs-on: ubuntu-latest
    needs: ServiceNow-GitHub-Actions-Test-Basic-Auth
    steps:
       - name: Run Tests HMAC Token
         uses: mikevdberge/sncicd-tests-run@1.0.12
         with:
            testSuiteSysId: 891763283b5c22101680fec5e4e45a21
         env:
            nowHMACSecret: ${{ vars.NOW_HMAC_SECRET }}            
            nowKeyID:  ${{ vars.NOW_KEY_ID }}
            nowFullInstance: ${{ vars.NOW_FULL_INSTANCE }}            
