name: ServiceNow GitHub Action tester

on:
  workflow_dispatch:

jobs:
  ServiceNow-GitHub-Actions-Test:
    environment: LEGACY  
    runs-on: ubuntu-latest
    steps:
       - name: Run Tests Legacy
         uses: mikevdberge/sncicd-tests-run@1.0.10
         environment: LEGACY
         with:
            testSuiteSysId: 891763283b5c22101680fec5e4e45a21
         env:
            nowUsername: ${{ secrets.NOW_USERNAME }}
            nowPassword: ${{ secrets.NOW_PASSWORD }}
            nowApikey:  ${{ secrets.NOW_APIKEY }}
            nowInstallInstance: ${{ secrets.NOW_INSTALL_INSTANCE }}

  ServiceNow-GitHub-Actions-Test-API-Key:
    environment: API-KEY  
    runs-on: ubuntu-latest
    steps:
       - name: Run Tests API Key
         uses: mikevdberge/sncicd-tests-run@1.0.10
         with:
            testSuiteSysId: 891763283b5c22101680fec5e4e45a21
         env:
            nowApikey:  ${{ secrets.NOW_APIKEY }}
            nowFullInstance: ${{ secrets.NOW_FULL_INSTANCE }}
