name: ServiceNow GitHub Action tester

on:
  workflow_dispatch:

jobs:
  ServiceNow-GitHub-Actions-Test:
    runs-on: ubuntu-latest
    steps:
       - name: Run Tests 
         uses: mikevdberge/sncicd-tests-run@1.0.2
         with:
            testSuiteSysId: 123
         env:
            nowUsername: ${{ secrets.NOW_USERNAME }}
            nowPassword: ${{ secrets.NOW_PASSWORD }}
            nowApikey:  ${{ secrets.NOW_APIKEY }}
            nowInstallInstance: ${{ secrets.NOW_INSTALL_INSTANCE }}
